add var in for loop
If exif-js is required as a module then it throws an `Uncaught
ReferenceError: n is not defined`. Added the proper scoping with var in
order to solve this.